HW1
ok-technopolis-2020/Shabinsky_Dmitry pull request #1
Opened 2020-10-07 02:22 UTC by sdimosik

2020-10-09 11:34 UTC, fromanywhere requested changes

2020-10-09 11:34 UTC, fromanywhere commented on todo.html
> +            <details>
MDN пишет:
The HTML Details Element creates a disclosure widget in which information is visible only when the widget is toggled into an "open" state.

У нас тут вроде бы состояния открытости/закрытости списка нет

2020-10-09 11:34 UTC, fromanywhere commented on todo.html
> +                <summary>What needs to be done?</summary>
тут два интерактивных элемента: кнопка и однострочное поле ввода текста

2020-10-09 11:34 UTC, fromanywhere commented on todo.html
> +                <div class="list_task">
Лучше сделать это списком и с точки зрения разметки тоже

2020-10-09 11:34 UTC, fromanywhere commented on todo.html
> +                        <input type="checkbox" id="check1"><label for="check1">HTML</label>
Лайк за айдишки!

2020-10-09 11:34 UTC, fromanywhere commented on todo.html
> +                        <input type="button" id="delete_check2" value="x"><Br>
раз уж у нас не форма, пусть лучше будет `<button />`

2020-10-09 11:34 UTC, fromanywhere commented on todo.html
> +                <div class="down_toolbar">
Это всё-таки `<footer>`

2020-10-09 11:34 UTC, fromanywhere commented on todo.html
> +                    <input type="text" name="items_left" value="3 items left" disabled>
Ну, нет, это точно не поле ввода. Просто текст

2020-10-09 11:34 UTC, fromanywhere commented on todo.html
> +                    <input type="button" id="button1" value="All">
Здесь есть иерархия: фильтр из трех состояний и отдельно от него кнопка. Фильтр имеет уникальные состояния, поэтому радиокнопки

2020-10-14 22:57 UTC, sdimosik commented on todo.html
> +            <details>
Он пишет, что по умолчанию у нас закрыт details, но мы можем применить "open", чтобы при загрузке страницы элементы внутри было видно

2020-10-14 23:05 UTC, sdimosik commented
@fromanywhere вроде всё исправил)

2020-10-15 09:20 UTC, fromanywhere requested changes

2020-10-15 09:20 UTC, fromanywhere commented on todo.html
> +    <style>
рановато

2020-10-15 09:20 UTC, fromanywhere commented on todo.html
> +                <button class="main-controls__input-area-button">✔</button>
aria не хватает

2020-10-15 09:20 UTC, fromanywhere commented on todo.html
> +                    <input type="button" id="delete_check-1" aria-label="delete HTML" value="x">
лучше `<button>`
зачем `id`?

2020-10-15 09:20 UTC, fromanywhere commented on todo.html
> +                    <Br>
`<br>` не нужен

2020-10-15 09:20 UTC, fromanywhere commented on todo.html
> +                <label class="task-filter__item">
здесь лучше табы завернуть дополнительно в отдельный узел. Это всё-таки логически отдельный компонент

2020-10-15 16:06 UTC, sdimosik commented on todo.html
> +                    <input type="button" id="delete_check-1" aria-label="delete HTML" value="x">
ну id же нужен, чтобы сразу (тип уникальное значение) можно было привязывать какие-то действия к кнопке, например скрипты там

2020-10-15 17:10 UTC, sdimosik commented
@fromanywhere исправил

2020-10-16 12:44 UTC, fromanywhere commented on todo.html
> +                    <input type="button" id="delete_check-1" aria-label="delete HTML" value="x">
скрипты могут привязываться по произвольному селектору. Ладно бы связывали с каким-то labelом, я бы еще понял

2020-10-16 12:45 UTC, fromanywhere approved these changes

2020-10-16 12:45 UTC, fromanywhere commented on todo.html
> +                <button name="clear-button" type="submit" aria-label="clear completed tasks">Clear
здесь лучше без type

2020-10-16 15:13 UTC, merged