Add HW2
ok-technopolis-2020/Shabinsky_Dmitry pull request #2
Opened 2020-10-30 04:27 UTC by sdimosik

2020-10-30 10:28 UTC, fromanywhere requested changes

2020-10-30 10:28 UTC, fromanywhere commented on style1.css
> +    width      : 490px;
увеличиваем площадь ввода, отказываемся от указания явных значений по-возможности 
![image](https://user-images.githubusercontent.com/1042969/97693806-c1a13300-1ab2-11eb-99a2-0947a652fe40.png)

2020-10-30 10:28 UTC, fromanywhere commented on style1.css
> +    overflow        : auto;
оно вроде и так такое

2020-10-30 10:28 UTC, fromanywhere commented on style1.css
> +    font-family   : Roboto;
тут лучше указывать через запятую семейство, а еще заметно, что шрифт не подгрузился

2020-10-30 10:28 UTC, fromanywhere commented on style1.css
> +    width        : 25px;
делаем площадь клика больше

2020-10-30 10:28 UTC, fromanywhere commented on style1.css
> +    font-style : normal;
рвется 
![image](https://user-images.githubusercontent.com/1042969/97694038-1ba1f880-1ab3-11eb-9930-2ebfe0f0be5a.png)

2020-10-30 10:28 UTC, fromanywhere commented on style1.css
> +.todo-app__main-controls button {
классный бэм и зачем-то селектор по тегу тут. Не надо этого

2020-10-30 10:28 UTC, fromanywhere commented on style1.css
> +    margin     : 0 10px 0 0;
flex-grow: 1 поможет прижать крестик вправо

2020-10-30 10:28 UTC, fromanywhere commented on style1.css
> +    background: no-repeat center url(done-not-active.svg);
текстура смещается на пиксел вниз и вправо на клик
![screencast 2020-10-30 13-26-15](https://user-images.githubusercontent.com/1042969/97694464-a97de380-1ab3-11eb-9510-bd8f9f7989bd.gif)

2020-10-30 10:28 UTC, fromanywhere commented on style1.css
> +    background-color: var(--frame-color);
а тени?

2020-10-31 11:39 UTC, fromanywhere requested changes

2020-10-31 11:39 UTC, fromanywhere commented on css/style1.css
> +    border-radius   : 6px;
тут нужно не забыть position: relative — сейчас псевдоэлементы улетают

2020-10-31 11:39 UTC, fromanywhere commented on css/style1.css
> +    content   : '';
кажется, им не хватает белого фона и top: 0 — без этого располагаются в поток иначе

2020-10-31 11:39 UTC, fromanywhere commented on css/style1.css
> +    border-radius   : 6px;
из-за бордер-радиуса добавилось проблем — уголки шумят

2020-10-31 11:39 UTC, fromanywhere commented on css/style1.css
> +    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.2),
кажется, тут многовато теней

2020-10-31 11:39 UTC, fromanywhere commented on css/style1.css
> +    display: none;
вот тут мы теряем возможность клавиатурной навигации. Нужно придумать иной способ скрытия

2020-10-31 11:39 UTC, fromanywhere commented on css/style1.css
> +.label-item label {
везде же уже бэм, ну, селекторы по тегам не нужны. Пишем ему тоже класс свой

2020-11-06 15:08 UTC, fromanywhere requested changes

2020-11-06 15:08 UTC, fromanywhere commented on css/style1.css
> +    justify-content : center;
зарезается на узком экране, min-width 
![image](https://user-images.githubusercontent.com/1042969/98380332-7a3e1800-2059-11eb-84bd-56c67016c6e1.png)

2020-11-06 15:08 UTC, fromanywhere commented on css/style1.css
> +    display: none;
Всё еще теряем фокусы на табах

2020-11-06 15:08 UTC, fromanywhere commented on css/style1.css
> +    display      : table;
не надо это делать таблицей. Это flex-grow: 1; min-width: 0; без ширины

2020-11-06 15:08 UTC, fromanywhere commented on css/style1.css
> +    box-shadow    : inset 0px -1px 0px var(--shadow-color);
делаем границы бордерами, а не тенями

2020-11-06 17:15 UTC, sdimosik commented
@fromanywhere 
Исправил

2020-11-06 18:36 UTC, fromanywhere approved these changes

2020-11-06 18:38 UTC, merged